name: Delayed File Deletion

on:
  workflow_dispatch: # Manually trigger the workflow

jobs:
  delete-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Wait for 1 minute
        run: sleep 60

      - name: Delete file
        run: |
          rm -f greeta.py
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add -u
          git commit -m "Deleted example.txt after delay"
          git push origin main
