name: Run Python Script

on:
  push:
    branches:
      - main
  schedule:
    # Run every two minutes
    - cron: '*/2 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Python script
        run: |
          python say_hello.py
          
      - name: Commit results
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add result.txt
          git commit -m 'Updated result.txt with new message'
          git push origin ${{ github.ref }}
